apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite-deployment
  labels:
    app: personal-site
spec:
  replicas: 3
  selector:
    matchLabels:
      app: personal-site
  template:
    metadata:
      labels:
        app: personal-site
    spec:
      containers:
      - name: personal-site
        image: docker.io/oyhetola/personal-site:latest
        command: [ "sleep" ]
        args: [ "infinity" ]
        ports:
        - containerPort: 80